name: Sync Fork with Upstream

# Run the job every day at 00:00 UTC
on:
  schedule:
    - cron: "0 0 * * *"

# You can also trigger it manually using workflow_dispatch if needed
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Forked Repository
      uses: actions/checkout@v3
      with:
        # Ensure the repository history is available for the rebase
        fetch-depth: 0

    # Step 2: Set up Git user information for the commit
    - name: Set up Git user
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    # Step 3: Add the upstream repository
    - name: Add Upstream Repo
      run: |
        git fetch upstream

    # Step 4: Rebase the default branch of your fork onto upstream's default branch
    - name: Rebase from Upstream
      run: |
        git checkout main  # Replace 'main' with the default branch of your fork if different
        git rebase upstream/main

    # Step 5: Push the changes to your fork
    - name: Push Changes
      run: |
        git push origin main --force-with-lease  # Pushes the rebased changes to your fork's default branch
